apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story
          image: sebastianzee/kub-data-demo:2
          env:
            - name: STORY_DIR
              # value: 'story'
              valueFrom:
                configMapKeyRef:
                  name: data-store-env
                  key: directory
          volumeMounts:
            - mountPath: /app/story
              name: story-volume
      volumes:
        - name: story-volume
          # emptyDir: {}
          # hostPath:
          #   path: /data # On the host machine (the node)
          #   type: DirectoryOrCreate
          persistentVolumeClaim:
            claimName: host-pvc
